name: Commitlint

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  commitlint:
    name: Lint commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all commits.

      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.ts
